server:
  port: 10001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.202.116:3306/cloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    max-wait: 60000
    max-active: 100
    min-idle: 10
    initial-size: 10
#    type: com.mysql.cj.jdbc.MysqlDataSource
