server:
  port: 10002
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.16.0.127:3306/tms?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: Yupei.123
    max-wait: 60000
    max-active: 100
    min-idle: 10
    initial-size: 10
#    type: com.mysql.cj.jdbc.MysqlDataSource